### ISSUE TITLE
Review for NLDI

### ISSUE THREAD

**Issue by wadewswc** [WSWCWaterDataExchange/WaDESchemav0.3#1]
This draft schema for WaDE v0.3 needs a review to make sure it can support indexing. Please see the accompanying Excel files/pdf. The blue cells are headers. The orange cells are additions or modifications that need to be made.

**Comment by dblodgett-usgs** [comment]
A couple comments.

It seems like this could go in it's own table, but I don't think it's a problem to have the content denormalized at this stage. Long term, I could see this getting turned into one table though.

NHDVersion is going to be interesting. -- I don't think the NHD publishes versions for their high res, just a date. Maybe some guidance on that field is in order? We could also push on NGP to publish some kind of versioning guidance. The NHDPlus V1 and V2 are easy, but there's also NHDPlus Medium Res and High Res which are just going to come with a date. So... not entirely sure what to do with this one. As is the schema will handle what we need though, it's going to be a string. The other way to do this would be to have an NHD Data Product choice here. NHDPlus V1, NHDPlus V2, NHD Med Res, and NHD High Res. That plus the date would get us what we need.

I think reach code is an integer. Maybe ok to do it as a decimal, but if integer is possible, it's probably best.

It would be great if the lat/lon columns could be PostGIS data types... https://postgis.net/docs/using_postgis_dbmanagement.html#PostGIS_Geography I'm sure we could write a simple view or ETL that would convert the raw lat/lon into PostGIS types for use in a GIS though, so doing it this way (which doesn't require PostGIS) is probably fine.

+1 on the data quality fields. Will be interesting to see how those get adopted.

**Comment by wadewswc** [comment]
I have modified the NHDVersion to request the NHDProduct instead, with some provided guidance about what to enter into this field. This change, combined with the NHDUpdateDate should get what we want. Lat and longs were kept because some states use MSSQL and might not be using PostGIS. Hope that's okay. Thanks for the feedback on the data quality too. That's a big deal! ;) We'll see how many providers use them.
